name: Docker login
on: workflow_dispatch
jobs:
  docker-login:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Login
        uses: docker/login-action@v3.6.0
        with:
          username: ${{ vars.USERNAME }}
          password: ${{ secrets.PASSWORD }}
  
  
